version: '3.3'

services:

  oracle:
    image: gvenzl/oracle-xe:21-slim        
    container_name: oracledatabase 
    volumes:      
      - ./oracle-volume:/opt/oracle/oradata      
      - ./startupscripts:/container-entrypoint-startdb.d  
      - ./backup:/backup
    ports:    
      - 1521:1521
    environment:
      ORACLE_PASSWORD: root
      ORACLE_DATABASE : eis
      APP_USER: dbuser
      APP_USER_PASSWORD: dbuser

volumes: 
  oracle-volume:   
  startupscripts:
  backup: